import { notFound } from "next/navigation"
import PortfolioClient from "./PortfolioClient"

/* ─────────────────────────────────────────────────────────────
   Dados dos projetos
   ───────────────────────────────────────────────────────────── */
const PORTFOLIO = {
  droneiros: {
    name: "Droneiros Voluntários",
    projectType: "App Mobile · Dashboard",
    accent: "#F97316",
    bg: "#3D1206",
    tags: ["UX Design", "UI Design", "App Mobile", "Dashboard", "Identidade"],
    clientQuote: "Transformamos um sistema academicamente funcional em operacionalmente viável. Não redesenhamos telas — reestruturamos como confiança é estabelecida entre voluntários e coordenadores em contextos críticos.",
    clientName: "Equipe Droneiros",
    clientRole: "Voluntários de Resgate · Brasil",
    overview: "Plataforma que conecta pilotos de drone voluntários a Defesa Civil durante emergências naturais no Brasil. O desafio não era \"melhorar usabilidade\" — era viabilizar operação real.\n\nSistema existia mas não funcionava: matching manual em base de 800+ pilotos, dados inconsistentes impedindo filtros, nenhum critério objetivo de capacidade gerando insegurança mútua.\n\nSolução construída em camadas: sistema de níveis automático baseado em dados concretos, fluxos distintos para emergência vs planejamento, reestruturação completa de campos de dados, e gamificação para retenção de voluntários.\n\nResultado: matching automático viável, confiança estabelecida através de transparência, base sólida para escalar de projeto acadêmico para ferramenta profissional servindo coordenadores municipais e estaduais.\n\nDesign estratégico que resolve ansiedade, não apenas interface.",
    industry: "Resgate Civil",
    year: "2025",
    location: "Rio de Janeiro - Brasil",
    siteUrl: "/droneiros",
    siteThumb: "/droneiros/bg-droneiro.jpg",
    dsUrl: null,
    dsThumb: null,
    pdfUrl: "/portfolio-droneiro.pdf",
    pdfThumb: "/droneiros/bg-droneiro-doc.jpg",
  },
  imobiliaria: {
    name: "Horizonte Imóveis",
    projectType: "Web · Design System",
    accent: "#FFE600",
    bg: "#0E0D0D",
    tags: ["UX Design", "UI Design", "Design System", "Web", "Branding"],
    clientQuote: "Queríamos mais do que um site, precisávamos de uma plataforma que refletisse nossa história de 15 anos e convertesse visitantes em clientes com confiança.",
    clientName: "Equipe Comercial",
    clientRole: "Diretoria · Horizonte Imóveis",
    overview: "Plataforma web completa para imobiliária de alto padrão, com design system próprio, sistema de busca e filtragem avançada de imóveis, seções de equipe, depoimentos e soluções. Interface orientada a conversão, com identidade visual sólida e hierarquia de conteúdo clara.",
    industry: "Imobiliário",
    year: "2024",
    location: "São Paulo, Brasil",
    siteUrl: "/imobiliaria",
    siteThumb: "/droneiros/bg-imobiliaria.png",
    dsUrl: "/imobiliaria/design-system",
    dsThumb: "/droneiros/bg-imobiliaria-ds.png",
    pdfUrl: null,
    pdfThumb: null,
  },
  dentista: {
    name: "SorrisoJá",
    projectType: "Landing Page",
    accent: "#F0F0EE",
    bg: "#04131F",
    tags: ["UI Design", "Landing Page", "Conversão", "Identidade"],
    clientQuote: "Precisava de uma página que convertesse visitantes em pacientes agendados, sem complicação.",
    clientName: "Dr. Rafael Menezes",
    clientRole: "Dentista · SorrisoJá",
    overview: "Landing page focada em conversão para clínica odontológica. Design clean, copy direta e CTAs estratégicos para agendamento online.",
    industry: "Saúde",
    year: "2024",
    location: "Brasil",
    siteUrl: "/portfolio/landingpages/dentista",
    siteThumb: "/droneiros/sorrisobg.png",
    dsUrl: "/portfolio/landingpages/dentista/design-system",
    dsThumb: "/droneiros/sorrisobgds.png",
    pdfUrl: null,
    pdfThumb: null,
  },
  veterinario: {
    name: "Pata Vida",
    projectType: "Landing Page",
    accent: "#22C55E",
    bg: "#0B2615",
    tags: ["UI Design", "Landing Page", "Conversão", "Branding"],
    clientQuote: "Queríamos uma presença digital que passasse cuidado e profissionalismo para tutores de pets.",
    clientName: "Dr. Carlos Mendes",
    clientRole: "Veterinário · Pata Vida",
    overview: "Landing page para clínica veterinária com foco em transmitir cuidado e confiança. Estrutura pensada para conversão de novos tutores.",
    industry: "Veterinário",
    year: "2024",
    location: "Brasil",
    siteUrl: "/portfolio/landingpages/veterinario",
    siteThumb: "/droneiros/bgpatapetcard.png",
    dsUrl: "/portfolio/landingpages/veterinario/design-system",
    dsThumb: "/droneiros/bgpatavidacardds.png",
    pdfUrl: null,
    pdfThumb: null,
  },
  psicologa: {
    name: "Camila Magalhães",
    projectType: "Landing Page",
    accent: "#E2C9A8",
    bg: "#0E0D0E",
    tags: ["UI Design", "Landing Page", "Conversão", "Branding", "Saúde Mental"],
    clientQuote: "Queria uma presença digital que transmitisse acolhimento e profissionalismo para quem busca apoio psicológico.",
    clientName: "Camila Magalhães",
    clientRole: "Psicóloga Clínica · CRP 06/220072",
    overview: "Landing page para psicóloga clínica especializada em TCC e Acolhimento Emocional. Design sereno e humanizado, com foco em gerar confiança e converter visitantes em pacientes. Estrutura completa: hero, sobre, serviços, processo de agendamento, Instagram e contato direto via WhatsApp.",
    industry: "Saúde Mental",
    year: "2025",
    location: "Brasil",
    siteUrl: "https://psicamilamagalhaes.com.br",
    siteThumb: "/droneiros/bgpsicologa.png",
    dsUrl: null,
    dsThumb: null,
    pdfUrl: null,
    pdfThumb: null,
  },
  doutores: {
    name: "Doutores da Alegria",
    projectType: "Site Institucional",
    accent: "#FF61B5",
    bg: "#380A22",
    tags: ["UX Design", "UI Design", "Site Institucional", "ONG", "Branding"],
    clientQuote: "Queríamos um site que traduzisse em digital a mesma alegria e impacto que levamos há 30 anos para dentro dos hospitais públicos.",
    clientName: "Equipe Doutores da Alegria",
    clientRole: "ONG · Arte e Saúde · Brasil",
    overview: "Site institucional para uma das ONGs mais reconhecidas do Brasil — 30 anos levando a arte do palhaço a hospitais públicos.\n\nO desafio era traduzir uma identidade visual vibrante e emocional para uma experiência digital que ao mesmo tempo encantasse e convertesse: doadores, voluntários e parceiros institucionais, cada um com jornadas distintas.\n\nEstrutura pensada em camadas de impacto: hero com peso emocional imediato, seções de missão com dados concretos de alcance, e CTAs claros para doação e engajamento.\n\nDesign que celebra alegria sem perder credibilidade institucional — equilibrando paleta colorida (pink, amarelo, verde) com hierarquia de conteúdo séria e acessível.",
    industry: "ONG · Terceiro Setor",
    year: "2025",
    location: "São Paulo, Brasil",
    siteUrl: "https://doutoresdaalegria.org.br",
    siteThumb: "/droneiros/bghomedoutores.png",
    dsUrl: null,
    dsThumb: null,
    pdfUrl: null,
    pdfThumb: null,
  },
  moms: {
    name: "MOMS Cupons",
    projectType: "Landing Page · E-commerce",
    accent: "#FF6600",
    bg: "#1C1C2E",
    tags: ["UI Design", "Landing Page", "E-commerce", "UX Design", "Cupons"],
    clientQuote: "Precisávamos de uma plataforma que transformasse a busca por cupons em uma experiência visual e intuitiva, com foco em conversão e engajamento.",
    clientName: "Equipe MOMS",
    clientRole: "Agregador de Cupons · E-commerce",
    overview: "Landing page para agregador de cupons e descontos com curadoria de lojas parceiras.\n\nDesafio central: organizar um volume alto de informações (cupons, categorias, lojas) sem gerar sobrecarga cognitiva, mantendo o usuário focado na ação de copiar e usar o desconto.\n\nEstrutura construída em camadas de intenção: hero com acesso rápido às lojas populares, seção de cupons por categoria com carrossel interativo, lista filtrada por tipo de oferta e sidebar com atalhos contextuais.\n\nDesign orientado a conversão com hierarquia clara: o botão 'Ver Cupom' é o único CTA de destaque em toda a página, eliminando distração e maximizando cliques.\n\nPaleta laranja sobre branco e escuro transmite energia e confiança — a marca que está ao lado do consumidor na hora da economia.",
    industry: "E-commerce · Marketplace",
    year: "2025",
    location: "Brasil",
    siteUrl: "/portfolio/landingpages/moms",
    siteThumb: "/droneiros/momsbg.png",
    dsUrl: null,
    dsThumb: null,
    pdfUrl: null,
    pdfThumb: null,
  },
}

export function generateStaticParams() {
  return Object.keys(PORTFOLIO).map((slug) => ({ slug }))
}

export default async function PortfolioDetail({
  params,
}: {
  params: Promise<{ slug: string }>
}) {
  const { slug } = await params
  const p = PORTFOLIO[slug as keyof typeof PORTFOLIO]
  if (!p) notFound()

  return <PortfolioClient p={p} />
}
